services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user_test
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_test -d finance_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: transactions_routine_app
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: "postgres://user_test:password123@db:5432/finance_db?sslmode=disable"
      PORT : 8080
    ports:
      - "8080:8080"

volumes:
  postgres_data: